name: Go Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run tests with race detector
      run: go test -race -v ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v7
      with:
        version: latest

    - name: Build
      run: go build -v -o app ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.go-version }}
        path: ./app